# Project 4, Git Practice, APS1070 Fall 2022
#### **Linear Regression -  14 points**
**Deadline: Dec 1st, 21:00**

**Academic Integrity**

This project is individual - it is to be completed on your own. If you have questions, please post your query in the APS1070 Piazza Q&A forums (the answer might be useful to others!).

Do not share your code with others, or post your work online. Do not submit code that you have not written yourself. Students suspected of plagiarism on a project, midterm or exam will be referred to the department for formal discipline for breaches of the Student Code of Conduct.

Please fill out the following:


*   Your **name**: Anbumanivel Mohan Suganthi
*   Your **student number**: 1008696653

## Gradient Descent with Additional Features and Regularization [2 marks + 1 mark Git submission]

We'll apply linear regresssion to a toy dataset (`LR_data.csv`), with 10 features `x1`-`x10` and a "measurement" `y`. We'll take a few shortcuts by using built-in sklearn functions.

1. Data Preparation **[0.5]**
  * Print the dataset, and create Numpy arrays with inputs (X) and outputs (y). 
  * Split the dataset into training and validation sets (80% training, 20% validation). When splitting, set `random_state=1`.

2. Linear Regression **[0.5]**
  * Standardize the data using StandardScaler from sklearn.
  * Use the `sklearn.linear_model.LinearRegression` function [here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) to perform linear regression.
  * Print the RMSE for training and validation data.

3. Linear Regression with Additional Features **[0.5]**
  * Let's add more features to our dataset (degree 8) using `sklearn.preprocessing.PolynomialFeatures` [here](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html). You'll want to create the additional features first, then perform standardization (start from non-standardized data).
  * Again, use `sklearn.linear_model.LinearRegression` to perform linear regression.
  * Print the RMSE for training and validation data.

4. Linear Regression with Additional Features and Regularization **[0.5]**
  * Let's switch models, and instead use the `sklearn.linear_model.Ridge` function [here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge) to perform linear regression with regularization. Apply the model to the processed data (additional, standardized) you used in 3 above. Use a `FOR` loop to run `sklearn.linear_model.Ridge` with different `alpha` values. Specifically, sweep `alpha` from 1E-2 to 1E10 (each step is an order of magnitude jump).

In [1]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/aps1070-2019/datasets/master/LR_data.csv" , skipinitialspace=True)

In [2]:
df

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,1.454481,4.940543,7.116015,3.805131,4.105432,1.832290,5.211909,5.088293,3.841250,6.121133,6.575066e+06
1,4.907182,1.653654,7.339445,9.065282,7.169233,2.354136,2.893005,8.720131,8.646473,3.806860,8.419881e+06
2,1.842804,1.183878,4.203206,6.815847,6.655899,8.295816,3.556779,5.794679,3.260723,5.463808,9.745537e+04
3,2.393457,0.094127,3.208929,0.497443,4.318127,4.999247,9.470238,3.061990,7.312995,5.475240,1.129200e+04
4,5.093724,3.905293,4.858562,4.465484,0.947091,9.410307,8.137329,9.043838,9.128607,0.790795,3.105448e+05
...,...,...,...,...,...,...,...,...,...,...,...
195,2.936450,2.094812,9.493814,3.411240,4.350940,0.386062,1.303290,2.699563,7.622569,3.037162,6.599726e+07
196,4.915597,1.953974,7.312552,9.331203,1.329366,8.286760,5.233018,7.476923,7.043560,5.745565,8.176250e+06
197,6.772096,6.406489,4.638352,7.042340,0.912338,7.568296,1.194928,2.592840,9.386478,4.147710,2.144147e+05
198,3.940339,4.330498,6.693371,9.169265,0.858846,0.601942,2.635455,2.037859,7.883720,8.525164,4.028735e+06
199,8.636129,1.272939,4.339175,4.417427,5.697190,8.944253,7.952686,4.917967,9.543772,5.673870,1.257168e+05

In [3]:
import numpy as np
column = list(df.columns)
column_y = column.pop(-1)
column_X = column
column_X

['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10']

In [4]:
X = df[column_X].to_numpy()
y = df[column_y].to_numpy()
X

array([[1.45448096, 4.94054287, 7.11601489, ..., 5.08829321, 3.84125023,
        6.12113346],
       [4.90718225, 1.65365381, 7.33944456, ..., 8.72013079, 8.64647279,
        3.80685964],
       [1.84280389, 1.18387834, 4.20320584, ..., 5.79467869, 3.26072251,
        5.46380776],
       ...,
       [6.77209621, 6.40648915, 4.6383525 , ..., 2.59284   , 9.38647814,
        4.14770963],
       [3.94033913, 4.3304978 , 6.69337057, ..., 2.03785905, 7.88372005,
        8.52516391],
       [8.63612874, 1.27293914, 4.33917484, ..., 4.91796749, 9.54377194,
        5.67386964]])

In [5]:
# Splitting the data
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = 0, 0, 0, 0
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, random_state=1)
X_train.shape

(160, 10)

In [6]:
# Standaradizing the data
from sklearn.preprocessing import StandardScaler
scal = StandardScaler()
X_train_std = scal.fit_transform(X_train)
X_val_std = scal.transform(X_val)

In [7]:
def RMSE(x, y):
  ans = sqrt(mean_squared_error(x, y))
  return ans

In [8]:
# Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from math import sqrt
mdl = LinearRegression().fit(X_train_std, y_train)

y_pred_train = mdl.predict(X_train_std)
y_pred_val = mdl.predict(X_val_std)
RMSE_train = RMSE(y_pred_train, y_train)

# RMSE for training and validation sets
RMSE_val = RMSE(y_pred_val, y_val)
print("RMSE for training:", RMSE_train)
print("RMSE for validation:", RMSE_val)

RMSE for training: 16296980.655667374
RMSE for validation: 14061578.864980102

In [9]:
# Linear Regression with Additional Features
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=8)
X_poly_train = poly.fit_transform(X_train)
X_poly_val = poly.transform(X_val)

# Standardizing
scaler = StandardScaler()
X_poly_train_std = scaler.fit_transform(X_poly_train)
X_poly_val_std = scaler.transform(X_poly_val)

model = LinearRegression().fit(X_poly_train_std, y_train)
y_pred_poly_train = model.predict(X_poly_train_std)
y_pred_poly_val = model.predict(X_poly_val_std)

RMSE_poly_train = RMSE(y_pred_poly_train, y_train)
RMSE_poly_val = RMSE(y_pred_poly_val, y_val)
print("RMSE for training with additional features:", RMSE_poly_train)
print("RMSE for validation with additional features:", RMSE_poly_val)

RMSE for training with additional features: 1.1447930035368027e-07
RMSE for validation with additional features: 10920843.908991363

In [10]:
# Linear Regression with Additional Features and Regularization
from sklearn.linear_model import Ridge
RMSE_reg_train = []
RMSE_reg_val = []
alpha = [10**i for i in range(-2,11)]
alpha
for i in alpha:
  model_reg = Ridge(alpha=i).fit(X_poly_train_std, y_train)
  y_pred_reg_train = model_reg.predict(X_poly_train_std)
  y_pred_reg_val = model_reg.predict(X_poly_val_std)
  RMSE_reg_train.append(RMSE(y_pred_reg_train, y_train))
  RMSE_reg_val.append(RMSE(y_pred_reg_val, y_val))
df_table = pd.DataFrame(list(zip(alpha, RMSE_reg_train, RMSE_reg_val)), columns=['Alpha', 'Training RMSE', 'Validation RMSE'])
df_table

           Alpha  Training RMSE  Validation RMSE
0   1.000000e-02   3.210124e+02     1.091950e+07
1   1.000000e-01   3.199350e+03     1.091617e+07
2   1.000000e+00   3.098852e+04     1.088465e+07
3   1.000000e+01   2.480804e+05     1.065971e+07
4   1.000000e+02   1.196924e+06     9.484394e+06
5   1.000000e+03   3.609078e+06     5.633183e+06
6   1.000000e+04   7.712389e+06     4.521906e+06
7   1.000000e+05   1.460050e+07     1.050286e+07
8   1.000000e+06   2.003603e+07     1.605763e+07
9   1.000000e+07   2.291082e+07     1.870001e+07
10  1.000000e+08   2.343572e+07     1.917803e+07
11  1.000000e+09   2.349401e+07     1.923112e+07
12  1.000000e+10   2.349990e+07     1.923649e+07